server:
  port: 8081
# DataSource Config
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vueblog?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: root
    platform: mysql
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
#3.x的配置
mybatis-plus:
  #mapper-locations:
  #- classpath*:mapper/**/*Mapper.xml
  mapper-locations: classpath:/mapper/*.xml  # classpath*:/mapper/**Mapper.xml
  typeAliasesPackage: com.ren.entity

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379

ren:
  jwt:
    #加密钥匙
    secret: f4e2e52034348f86b667cde581c0f9eb5
    # token有效时长 7天  单位秒
    expire: 604800
    header: Authorization
#  global-config:
#    db-config:
#      select-strategy: not_empty
#      insert-strategy: not_empty
#      update-strategy: not_empty
#      id-type: auto
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false